<template>
  <q-page>
    <div class="row justify-center align-center q-mb-lg">
      <div class="col-6">
        <div class="row">
          <div class="col-12">
            <q-card
              class="no-shadow q-px-md q-pb-md"
              style="border: 1px solid #ccc"
            >
              <q-card-section>
                <div class="row justify-center">
                  <div class="text-h3">Terms & Service</div>
                </div>
              </q-card-section>
              <q-card-section>
                <q-card-main>
                  <div class="text-h4">1. Use of the Website</div>
                  <p>
                    1.1 User Conduct: You agree to use the Website responsibly
                    and in compliance with applicable laws and regulations. You
                    will not use the Website for any unlawful, harmful, or
                    fraudulent activities.
                  </p>
                  <p>
                    1.2 Age Restriction: The Website is intended for users who
                    are 18 years of age or older. If you are under the age of
                    18, you may only use the Website under the supervision of a
                    parent or legal guardian.
                  </p>

                  <div class="text-h4">2. Disclaimer of Liability</div>
                  <p>
                    2.1 Content Accuracy: The content generated by ChatGPT on
                    the Website is provided for informational purposes only. We
                    make no guarantee regarding the accuracy, completeness, or
                    usefulness of the content. You acknowledge that any reliance
                    on the content generated by ChatGPT is at your own risk.
                  </p>
                  <p>
                    2.2 Limitation of Liability: We shall not be held liable for
                    any direct, indirect, incidental, consequential, or special
                    damages arising out of or in connection with your use of the
                    Website, including but not limited to damages for loss of
                    profits, data, or other intangible losses.
                  </p>

                  <div class="text-h4">3. Intellectual Property</div>
                  <p>
                    3.1 Ownership: The Website and its contents, including but
                    not limited to text, graphics, images, and software, are the
                    property of the Website owner or its licensors and are
                    protected by intellectual property laws.
                  </p>
                  <p>
                    3.2 Limited License: We grant you a limited, non-exclusive,
                    non-transferable license to access and use the Website for
                    personal, non-commercial purposes. You may not modify,
                    reproduce, distribute, or create derivative works based on
                    the Website without our prior written consent.
                  </p>

                  <div class="text-h4">4. Privacy</div>
                  <p>
                    4.1 Data Collection: We may collect and process certain
                    personal information in accordance with our Privacy Policy.
                    By using the Website, you consent to the collection and
                    processing of your personal information as described in the
                    Privacy Policy.
                  </p>
                  <p>
                    4.2 Security: We strive to implement reasonable security
                    measures to protect your personal information. However, no
                    data transmission over the internet or electronic storage
                    method is completely secure, and we cannot guarantee the
                    absolute security of your information.
                  </p>

                  <div class="text-h4">5. Modifications and Termination</div>
                  <p>
                    5.1 Modifications: We reserve the right to modify, suspend,
                    or discontinue the Website or any part of it at any time
                    without prior notice.
                  </p>
                  <p>
                    5.2 Termination: We may terminate or suspend your access to
                    the Website immediately, without prior notice or liability,
                    for any reason whatsoever, including without limitation if
                    you breach these Terms.
                  </p>

                  <div class="text-h4">6. Governing Law</div>
                  <p>
                    These Terms shall be governed by and construed in accordance
                    with the laws of [Your Jurisdiction]. Any disputes arising
                    out of or relating to these Terms or the use of the Website
                    shall be subject to the exclusive jurisdiction of the courts
                    in [Your Jurisdiction].
                  </p>
                </q-card-main>
              </q-card-section>
            </q-card>
          </div>
        </div>
      </div>
    </div>
  </q-page>
</template>
<script>
import { defineComponent } from "vue";

export default defineComponent({
  name: "TermsService",
});
</script>
